#:schema node_modules/wrangler/config-schema.json
name = "yaendbot"
main = "src/index.ts"
compatibility_date = "2025-08-09"
compatibility_flags = ["nodejs_compat"]
minify = true
upload_source_maps = true
preview_urls = false

[[d1_databases]]
binding = "DB"
database_name = "yaendbot"
database_id = "a6220646-5813-4be2-82ad-1e7f94374295"

[observability]
enabled = true

[vars.BOT_INFO]
id = 7913290545
is_bot = true
first_name = "yaendbot"
username = "yaendbot"
can_join_groups = true
can_read_all_group_messages = true
supports_inline_queries = false
can_connect_to_business = false
has_main_web_app = false
